moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.14.5
project:
  name: wedding-invitation
  mode: personal
  description: ''
  created_at: '2026-01-27 13:27:31'
  optimized: false
  template_version: 1.14.5
